site_name: Zero to Mastery TensorFlow for Deep Learning
site_url: http://dev.mrdbourke.com/tensorflow-deep-learning/

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
 - mkdocs-jupyter
 - search

repo_url: https://github.com/mrdbourke/tensorflow-deep-learning/settings/pages
