site_name: Zero to Mastery TensorFlow for Deep Learning
site_url: http://dev.mrdbourke.com/tensorflow-deep-learning/

theme:
  name: material
  logo: assets/misc-ztm-logo.png
  features:
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
 - mkdocs-jupyter
 - search

repo_url: https://github.com/mrdbourke/tensorflow-deep-learning/
repo_name: mrdbourke/tensorflow_deep_learning

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrdbourke
    - icon: fontawesome/brands/github
      link: https://github.com/mrdbourke
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ
